# Generated by Django 3.1 on 2020-09-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainSkills', '0006_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
    ]
