# Generated by Django 3.1 on 2020-09-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainSkills', '0005_auto_20200912_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
