# Generated by Django 3.1 on 2020-09-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brainSkills', '0007_auto_20200923_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainSkills.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainSkills.teacher')),
            ],
            options={
                'unique_together': {('course', 'teacher')},
            },
        ),
    ]
