# Generated by Django 3.1 on 2020-09-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brainSkills', '0008_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainSkills.assign')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainSkills.student')),
            ],
        ),
    ]
